version: "3.6"

services:
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-central-1
    ports:
      - 8001:8001

  localstack:
    image: localstack/localstack:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
      - 8085:8080
