resources:
  - machine-id.yaml
helmCharts:
  - name: fluent-bit
    includeCRDs: false
    releaseName: fluent-bit
    namespace: fluent-bit
    version: 0.37.0
    repo: https://fluent.github.io/helm-charts
    valuesInline:
      #logLevel: debug
      prometheusRule:
        enabled: false
      daemonSetVolumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: etcmachineid
          configMap:
            name: etcmachineidcm

      daemonSetVolumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: etcmachineid
          mountPath: /etc/machine-id
          subPath: machine-id

      serviceMonitor:
        enabled: true
      config:
        inputs: |
          [INPUT]
              Name tail
              Path /var/log/containers/*.log
              multiline.parser docker, cri
              Tag kube.<namespace_name>.<pod_name>.<container_name>
              Tag_Regex (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
              Mem_Buf_Limit 50MB
              Skip_Long_Lines Off
              DB /var/log/state.db
        customParsers: |
          [PARSER]
              Name k8s-tags
              Format regex
              Regex /^(?<namespace_name>[^\.]+)\.(?<pod_name>[a-z0-9-]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)/

          [PARSER]
              Name        json-time-rfc3339
              Format      json
              Time_Format %Y-%m-%dT%H:%M:%S.%LZ
  
          [PARSER]
              Name        json-timestamp-rfc3339
              Format      json
              Time_Key    timestamp
              Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        filters: |
          [FILTER]
              Name                kubernetes
              Match               kube.*
              Merge_Log           On
              Keep_Log            Off
              Kube_Tag_Prefix     kube.
              Regex_Parser        k8s-tags
              K8S-Logging.Parser  On
              K8S-Logging.Exclude On
  
          [FILTER]
              Name          nest
              Match         kube.*
              Operation     lift
              Nested_under  kubernetes
              Add_prefix    kubernetes_
  
          [FILTER]
              Name          nest
              Match         kube.*
              Operation     lift
              Nested_under  kubernetes_labels
              Add_prefix    kubernetes_labels_
  
          [FILTER]
              Name          parser
              Match         kube.*
              Parser        json-time-rfc3339
              Parser        json-timestamp-rfc3339
              Key_Name      message
              Reserve_Data  True
  
          # rename msg field to message if msg field exists and message field does not exist
          [FILTER]
              Name          modify
              Match         kube.*
              Rename        msg message
  
          # block for tag naming strategy
          [FILTER]
              Name          modify
              Match         kube.*
              Copy          kubernetes_labels_eks.amazonaws.com/component logstream_name
              Copy          kubernetes_labels_strimzi.io/name logstream_name
              Copy          kubernetes_labels_app logstream_name
              Copy          kubernetes_labels_app.kubernetes.io/name logstream_name
              Copy          kubernetes_labels_app.kubernetes.io/instance logstream_name
              Copy          kubernetes_labels_k8s-app logstream_name
              Copy          kubernetes_labels_name logstream_name
              Add           logstream_name untagged

          # end of block for tag naming strategy
  
          [FILTER]
              Name    lua
              Match   kube.*
              code    function logstream_name_to_lowercase(tag, timestamp, record) new_record = record new_record["logstream_name"] = string.lower(record["logstream_name"]) return 1, timestamp, new_record end
              call    logstream_name_to_lowercase
  
          # rewrite tag to "<namespace_name>-<pod_name>
          [FILTER]
              Name                  rewrite_tag
              Match                 kube.*
              Rule                  $logstream_name (.*) $TAG[1]-$1 false
              Emitter_Mem_Buf_Limit 50M

        outputs: |
          [OUTPUT]
              Name        forward
              Match       *
              Host        fluentd.fluentd
              Port        15000
              Retry_Limit 5
